qyapi:
  base_url: 'https://qyapi.weixin.qq.com/'

  qiye_id: ""
  kefu_Secret: ""
  sToken: ""
  sEncodingAESKey: ""


chatgpt:
  proxy: "127.0.0.1:7890"
  model_name: "gpt-3.5-turbo-16k"
  api_key: "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"


secret:
  verify_userid: ""

